### PR TITLE
Update 'stacks' property description in the cloud_controller_ng spec

### PR DESCRIPTION
**Pull request by ishustava**
* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

### CODE REVIEW

**Comment by tcdowney** [comment]
Looks good to me 👍 thanks!

**Comment by tcdowney** [comment]
@ishustava can you update these descriptions in the `cloud_controller_clock` and `cloud_controller_worker` spec files as well?

Thanks!

**Comment by ishustava** [comment]
Hey @tcdowney, done!

**Comment by tcdowney** [comment]
Thanks! Looks good. 👍

**Pull request merged**
