### PR TITLE
Log rate limit changes

### PR DESCRIPTION
**Pull request by Benjamintf1**
Thanks for contributing to the `capi_release`. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
- add a default rate limit to capi

- Remove cc.temporary_use_logcache property

    New cloud controllers don't support using Traffic Controller for
    container metrics, so removing this property from capi-release
* An explanation of the use cases your change solves
Capi release changes for cloud controller ng for log rate limiting feature
* Links to any other associated PRs
https://github.com/cloudfoundry/cloud_controller_ng/pull/2900
* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [ ] I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by Benjamintf1** [comment]
NOTE: Shouldn't be merged before the cloud_controller_ng changes. Also, we need to look into making sure we have the default log limit in the right place and *only* in the right place.

**Comment by Benjamintf1** [comment]
Huh, looks like it's the case for other properties too. Seems not great, but not like a huge difference for this pr.

**Comment by sethboyles** [comment]
any reason to choose `9999` as opposed to `-1`?

**Comment by sethboyles** [comment]
@ctlong any reason to choose 9999 as opposed to -1?

**Comment by ctlong** [comment]
@sethboyles omg we definitely do not want to choose 9999. We should set a more appropriate value for sure, thanks for calling this out!

**Pull request merged**
