### PR TITLE
Adds cc.tls_port to provided link property

### PR DESCRIPTION
**Pull request by apoydence**
As a consumer of the internal TLS API, I would like to ensure that I hit the correct port.

Thanks for contributing to the `capi_release`. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

* An explanation of the use cases your change solves

* Links to any other associated PRs

* [X] I have viewed signed and have submitted the Contributor License Agreement

* [X] I have made this pull request to the `develop` branch

* [ ] I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by Benjamintf1** [comment]
Howdy! https://github.com/cloudfoundry/capi-release/commit/0b1ef76ed0941576471596fb154e631b5213fde5 This commit right here seems to include the proposed fix. @cloudfoundry/cf-capi any reason this is still open?

**Comment by tcdowney** [comment]
@Benjamintf1 I would not rely on anything added to the `cloud_controller_internal` link. It's actually just an experiment by our team to DRY up spec properties (and prevent divergent configuration) between BOSH jobs that our team owns (e.g. `cloud_controller_ng`, `cloud_controller_worker`, `cc_deployment_updater`, etc.). We don't actually intend for other BOSH releases to consume properties off of that specific link (although I can see how the name of it might be confusing for folks that consume our internal APIs). Let us know if you have any suggestions for making this distinction more clear.

I would keep this PR open since we'd want to expose this property under one of our "public" links. It's pretty old though, not sure why it hasn't been prioritized yet. cc @zrob

**Comment by zrob** [comment]
thanks for circling back on this issue.

I think there are actually more properties needed to make this connection convenient. 

I've proposed a link to use for this purpose in this [story](https://www.pivotaltracker.com/story/show/159800996).  Would appreciate feedback on its contents.

**Comment by zrob** [comment]
The linked story has finished up and should be available in the next capi-release

**Pull request closed without merging**
