### PR TITLE
Fix shellcheck errors

### PR DESCRIPTION
**Pull request by gerhard**
- [x] I have viewed signed and have submitted the Contributor License Agreement
- [x] I have made this pull request to the `master` branch
- [ ] I have run CF Acceptance Tests on bosh lite

### CODE REVIEW

**Comment by sax** [comment]
Hi @gerhard!

Thanks for taking the time to run this through a linter. I'm not able to reproduce the lint errors, however... can you explain how you're running `shellcheck` in order to generate the errors that you're fixing?

We are using shellcheck as installed by homebrew, and do not see any linting errors when we run it locally.

**Comment by gerhard** [comment]
I'm also using homebrew shellcheck, the versions that we're running might be different:

```sh
$ shellcheck -V
ShellCheck - shell script analysis tool
version: 0.4.4
license: GNU General Public License, version 3
website: http://www.shellcheck.net

$ shellcheck -s src/capi_utils/pid_utils.sh

In src/capi_utils/pid_utils.sh line 1:
function pid_is_running() {
^-- SC2112: 'function' keyword is non-standard. Delete it.


In src/capi_utils/pid_utils.sh line 2:
  declare pid="$1"
  ^-- SC2039: In POSIX sh, 'declare' is undefined.


In src/capi_utils/pid_utils.sh line 15:
function pid_guard() {
^-- SC2112: 'function' keyword is non-standard. Delete it.


In src/capi_utils/pid_utils.sh line 16:
  declare pidfile="$1" name="$2"
  ^-- SC2039: In POSIX sh, 'declare' is undefined.


In src/capi_utils/pid_utils.sh line 24:
  local pid
  ^-- SC2039: In POSIX sh, 'local' is undefined.


In src/capi_utils/pid_utils.sh line 47:
function wait_pid_death() {
^-- SC2112: 'function' keyword is non-standard. Delete it.


In src/capi_utils/pid_utils.sh line 48:
  declare pid="$1" timeout="$2"
  ^-- SC2039: In POSIX sh, 'declare' is undefined.


In src/capi_utils/pid_utils.sh line 50:
  local countdown
  ^-- SC2039: In POSIX sh, 'local' is undefined.


In src/capi_utils/pid_utils.sh line 81:
function kill_and_wait() {
^-- SC2112: 'function' keyword is non-standard. Delete it.


In src/capi_utils/pid_utils.sh line 82:
  declare pidfile="$1" timeout="${2:-25}" sigkill_on_timeout="${3:-1}"
  ^-- SC2039: In POSIX sh, 'declare' is undefined.


In src/capi_utils/pid_utils.sh line 89:
  local pid
  ^-- SC2039: In POSIX sh, 'local' is undefined.
```

[This](https://github.com/gerhard/setup) will create an identical setup to mine.

**Comment by adowns01** [comment]
Hi @gerhard, 

We were able to reproduce your errors by running `shellcheck -s sh src/capi_utils/pid_utils.sh`, however these scripts are run in bash and if you run `shellcheck -s bash src/capi_utils/pid_utils.sh` there are no errors. Is there any reason why you are running this in sh, not in bash?

Thanks, 
@adowns01 && @ardnaxelarak, CAPI Team Members

**Comment by gerhard** [comment]
The file extension is `.sh`, and with no shell shebang to overwrite this (i.e. `#!/bin/bash`), my code editor interprets them as sh scripts.

Given these are bash scripts, I agree that the current changes are not relevant. I see 2 options:

1. Add `#!/bin/bash` to the top of the file
1. Change the file extension from `.sh` to `.bash`

The first option will involve the least changes and is what I'm leaning towards. Happy to change this PR once we agree on the best option.

**Comment by sax** [comment]
@gerhard I went ahead and added shebangs to the files, as well as fixing some other shellcheck warnings in capi_utils (probably introduced after you started this pull request). Let us know if that looks good to you and if we can close this issue, or if you see any other issues.

https://github.com/cloudfoundry/capi-release/commit/89f9a49c0c649b896ddc8132d28c7bab383c2ce9

Thanks!

**Comment by gerhard** [comment]
Looks good, happy to close 👍

**Pull request closed without merging**
